source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in calendar_watcher.gemspec
gemspec
gem 'goohub', :git => 'https://github.com/nomlab/goohub'
