* CalendarWatcher

  Watch Google calendar and send events via gRPC to upstreams.

** Installation

   Add this line to your application's Gemfile:

   #+BEGIN_SRC ruby
     gem 'calendar_watcher'
   #+END_SRC

   And then execute:

   #+BEGIN_SRC ruby
     $ bundle
   #+END_SRC

   Or install it yourself as:

   #+BEGIN_SRC ruby
     $ gem install calendar_watcher
   #+END_SRC

** Setup

   CalendarWatcher requires authorization to Google Calendar API.

   1. Get OAuth 2.0 CLIENT_ID/CLIENT_SECRET at
      https://console.developers.google.com

   2. Create a config file by invoking init command.
     #+BEGIN_SRC ruby
     $ bundle exec exe/calendar_watcher init
     #+END_SRC

   3. Authorize by invoking auth command.
     #+BEGIN_SRC ruby
     $ bundle exec exe/calendar_watcher auth
     #+END_SRC

** Usage

   TODO: Write usage instructions here

** Development

   After checking out the repo,

   1. Install dependencies:
     #+BEGIN_SRC ruby
     $ cd calendar_watcher
     $ bundle install --path=vendor/bundle --binstubs=bin
     #+END_SRC

   2. Generate gRPC code:
     #+BEGIN_SRC ruby
     $ bundle exec rake compile
     #+END_SRC

   To install this gem onto your local machine, run
   =bundle exec rake install=. To release a new version,
   update the version number in
   =version.rb=, and then run =bundle exec rake release=, which will
   create a git tag for the version, push git commits and tags, and push
   the =.gem= file to [[https://rubygems.org][rubygems.org]].
   You don’t need to run =bundle exec rake compile= before running
   =bundle exec rake install= or =bundle exec rake release= because
   both of commands are dependencies of =bundle exec rake compile=.

** Contributing

   Bug reports and pull requests are welcome on GitHub at
   https://github.com/nomlab/hiyoco.

** License

   The gem is available as open source under the terms of the
   [[https://opensource.org/licenses/MIT][MIT License]].
