# Golang CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/configuration-reference/
#
version: 2
jobs:
  generate-docs:
    docker:
      - image: pseudomuto/protoc-gen-doc:1.1.0
        entrypoint: /bin/bash
    steps:
      - run:
          name: Install git
          command: |
            set +e
            apt-get -q -y update
            apt-get -q -y install git-core ssh-client
            apt-get autoremove
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Setup GitHub
          command: |
            set +e
            export USERNAME=$(git log --pretty=tformat:%an | head -1)
            export EMAIL=$(git log --pretty=tformat:%ae | head -1)
            git config --global user.email "${EMAIL}"
            git config --global user.name "${USERNAME}"
      - add_ssh_keys:
          fingerprints:
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"
      - checkout
      - run:
          name: Generate docs/ in proto/
          command: |
            set +e
            cd proto
            bash ./generate_docs.sh --local
      - run:
          name: Push to GitHub
          command: |
            set +e
            git add docs
            git commit --quiet -m "[ci skip] Update API docs

            ${CIRCLE_BUILD_URL}"
            git push origin ${CIRCLE_BRANCH}

workflows:
  version: 2
  all-jobs:
    jobs:
      - generate-docs:
          filters:
            branches:
              only:
                - master
