# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hiyoco/slacker/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hiyoco.calendar import event_pb2 as hiyoco_dot_calendar_dot_event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hiyoco/slacker/service.proto',
  package='hiyoco.slacker',
  syntax='proto3',
  serialized_pb=_b('\n\x1chiyoco/slacker/service.proto\x12\x0ehiyoco.slacker\x1a\x1bhiyoco/calendar/event.proto2F\n\x05Slack\x12=\n\x08SayEvent\x12\x16.hiyoco.calendar.Event\x1a\x17.hiyoco.calendar.Result\"\x00\x42\x42\n\x11org.nomlab.hiyocoB\x14SlackerServiceProtos\xaa\x02\x16Hiyoco.Slacker.Serviceb\x06proto3')
  ,
  dependencies=[hiyoco_dot_calendar_dot_event__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021org.nomlab.hiyocoB\024SlackerServiceProtos\252\002\026Hiyoco.Slacker.Service'))

_SLACK = _descriptor.ServiceDescriptor(
  name='Slack',
  full_name='hiyoco.slacker.Slack',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=77,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayEvent',
    full_name='hiyoco.slacker.Slack.SayEvent',
    index=0,
    containing_service=None,
    input_type=hiyoco_dot_calendar_dot_event__pb2._EVENT,
    output_type=hiyoco_dot_calendar_dot_event__pb2._RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLACK)

DESCRIPTOR.services_by_name['Slack'] = _SLACK

# @@protoc_insertion_point(module_scope)
