# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hiyoco/calendar/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hiyoco/calendar/event.proto',
  package='hiyoco.calendar',
  syntax='proto3',
  serialized_pb=_b('\n\x1bhiyoco/calendar/event.proto\x12\x0fhiyoco.calendar\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n\x04\x44\x61te\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"J\n\x08\x44\x61teTime\x12,\n\x08\x64\x61teTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08timeZone\x18\x02 \x01(\t\"p\n\nDateOrTime\x12%\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x15.hiyoco.calendar.DateH\x00\x12-\n\x08\x64\x61teTime\x18\x02 \x01(\x0b\x32\x19.hiyoco.calendar.DateTimeH\x00\x42\x0c\n\nDateOrTime\"\x83\x01\n\x05\x45vent\x12*\n\x05start\x18\x01 \x01(\x0b\x32\x1b.hiyoco.calendar.DateOrTime\x12(\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1b.hiyoco.calendar.DateOrTime\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\x42\x38\n\x11org.nomlab.hiyocoB\x0b\x45ventProtos\xaa\x02\x15Hiyoco.Calendar.Eventb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='hiyoco.calendar.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='hiyoco.calendar.Date.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=129,
)


_DATETIME = _descriptor.Descriptor(
  name='DateTime',
  full_name='hiyoco.calendar.DateTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='hiyoco.calendar.DateTime.dateTime', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeZone', full_name='hiyoco.calendar.DateTime.timeZone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=205,
)


_DATEORTIME = _descriptor.Descriptor(
  name='DateOrTime',
  full_name='hiyoco.calendar.DateOrTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='hiyoco.calendar.DateOrTime.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='hiyoco.calendar.DateOrTime.dateTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='DateOrTime', full_name='hiyoco.calendar.DateOrTime.DateOrTime',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=207,
  serialized_end=319,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='hiyoco.calendar.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='hiyoco.calendar.Event.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='hiyoco.calendar.Event.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='hiyoco.calendar.Event.summary', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hiyoco.calendar.Event.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=453,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='hiyoco.calendar.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='hiyoco.calendar.Result.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=479,
)

_DATE.fields_by_name['date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATETIME.fields_by_name['dateTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATEORTIME.fields_by_name['date'].message_type = _DATE
_DATEORTIME.fields_by_name['dateTime'].message_type = _DATETIME
_DATEORTIME.oneofs_by_name['DateOrTime'].fields.append(
  _DATEORTIME.fields_by_name['date'])
_DATEORTIME.fields_by_name['date'].containing_oneof = _DATEORTIME.oneofs_by_name['DateOrTime']
_DATEORTIME.oneofs_by_name['DateOrTime'].fields.append(
  _DATEORTIME.fields_by_name['dateTime'])
_DATEORTIME.fields_by_name['dateTime'].containing_oneof = _DATEORTIME.oneofs_by_name['DateOrTime']
_EVENT.fields_by_name['start'].message_type = _DATEORTIME
_EVENT.fields_by_name['end'].message_type = _DATEORTIME
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['DateTime'] = _DATETIME
DESCRIPTOR.message_types_by_name['DateOrTime'] = _DATEORTIME
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'hiyoco.calendar.event_pb2'
  # @@protoc_insertion_point(class_scope:hiyoco.calendar.Date)
  ))
_sym_db.RegisterMessage(Date)

DateTime = _reflection.GeneratedProtocolMessageType('DateTime', (_message.Message,), dict(
  DESCRIPTOR = _DATETIME,
  __module__ = 'hiyoco.calendar.event_pb2'
  # @@protoc_insertion_point(class_scope:hiyoco.calendar.DateTime)
  ))
_sym_db.RegisterMessage(DateTime)

DateOrTime = _reflection.GeneratedProtocolMessageType('DateOrTime', (_message.Message,), dict(
  DESCRIPTOR = _DATEORTIME,
  __module__ = 'hiyoco.calendar.event_pb2'
  # @@protoc_insertion_point(class_scope:hiyoco.calendar.DateOrTime)
  ))
_sym_db.RegisterMessage(DateOrTime)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'hiyoco.calendar.event_pb2'
  # @@protoc_insertion_point(class_scope:hiyoco.calendar.Event)
  ))
_sym_db.RegisterMessage(Event)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'hiyoco.calendar.event_pb2'
  # @@protoc_insertion_point(class_scope:hiyoco.calendar.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021org.nomlab.hiyocoB\013EventProtos\252\002\025Hiyoco.Calendar.Event'))
# @@protoc_insertion_point(module_scope)
